In [ ]:
# 1、完成nan和inf的使用，掌握数组中nan值去除，替换为对应列的平均值
# 2、np二维数组转置练习，轴滚动练习
# 3、练习series和df的索引操作,函数应用
# 4、练习处理缺失数据，统计与计算
# 
# 
# 操作与上课一致即可，完成基础作业即可提交
# 难度作业：
# 5、Numpy youtube数据读取练习，并通过matplotlib绘制直方图，散点图
# 6、练习对齐运算，层级索引，设置索引，时间序列
import numpy as np

In [13]:
# 第一题--nan
a = np.nan
b = np.inf
print(a, type(a))  # nan和inf都是float类型
print(b, type(b))

nan <class 'float'>
inf <class 'float'>


In [14]:
print(np.nan == np.nan)  # np.nan不等于np.nan
np.nan + 1

False


nan

In [17]:
t = np.arange(24, dtype=float).reshape(4, 6)

t[3, 4] = np.nan
t[2, 4] = np.nan
print(t)

#  可以借用np.nan!=np.nan来统计nan的个数
print(np.count_nonzero(t != t))  # 统计非零值
#  将nan替换成0
t[np.isnan(t)] = 0
print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. nan 17.]
 [18. 19. 20. 21. nan 23.]]
2
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15.  0. 17.]
 [18. 19. 20. 21.  0. 23.]]


In [22]:
t = np.arange(24).reshape(4, 6).astype(float)
t[1, 3:] = np.nan
print(t)
print(t.shape)
print(id(t))
# t.shape[1]  # t.shape就是元组(4,6)--所以t.shape[1]=6
for i in range(t.shape[1]):
    temp_col = t[:, i]  # 提取第i列

    nan_num = np.count_nonzero(temp_col != temp_col)
    if nan_num != 0:
        temp_col_not_nan = temp_col[temp_col == temp_col]
        print(temp_col_not_nan)
        temp_col[np.isnan(temp_col)] = np.mean(temp_col_not_nan)
print('-' * 50)
print(t)
print(id(t))
t[1, 3:] = np.nan
t1 = np.arange(24).reshape(4, 6).astype(float)
t + t1

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
(4, 6)
1556640633104
[ 3. 15. 21.]
[ 4. 16. 22.]
[ 5. 17. 23.]
--------------------------------------------------
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. 13. 14. 15.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
1556640633104


array([[ 0.,  2.,  4.,  6.,  8., 10.],
       [12., 14., 16., nan, nan, nan],
       [24., 26., 28., 30., 32., 34.],
       [36., 38., 40., 42., 44., 46.]])

In [23]:
# 第一题--inf
arr = np.array([-1, 0])
print(arr)
print(arr[0] / arr[1])


[-1  0]
-inf


C:\Users\Administrator\AppData\Local\Temp\ipykernel_18072\1207057292.py:4: RuntimeWarning: divide by zero encountered in scalar divide
  print(arr[0]/arr[1])


In [26]:
# 第二题--转置
a = np.arange(12).reshape(3, 4)
print('原数组\n', a)
print('对换数组\n', np.transpose(a))  # 类似于矩阵转置
print(a)  # a不变
print(a.T)  # T也是转置--更像矩阵了

原数组
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
对换数组
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [30]:
# 第二题--交换
t1 = np.arange(24).reshape(4, 6).astype(float)
# re1 = t1.swapaxes(1,0)
re1 = t1.swapaxes(0, 1)  # 效果一样
print(t1)
print(re1)
t3 = np.arange(60).reshape(3, 4, 5)
print(t3.shape)
t3 = np.swapaxes(t3, 1, 2)
print(t3.shape)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
[[ 0.  6. 12. 18.]
 [ 1.  7. 13. 19.]
 [ 2.  8. 14. 20.]
 [ 3.  9. 15. 21.]
 [ 4. 10. 16. 22.]
 [ 5. 11. 17. 23.]]
(3, 4, 5)
(3, 5, 4)


In [35]:
# 第二题--轴滚动
a = np.ones((3, 4, 5, 6))
b = np.rollaxis(a, 3, 1)  # 把第三轴放到原第一轴前，原自第一轴开始逐轴推迟
print(b.shape)
c = np.rollaxis(b, 1, 4)  # 把第一轴放到原第四轴前，然原无第四轴，则将第一轴放到最后面(最多写4
print(c.shape)

(3, 6, 4, 5)
(3, 4, 5, 6)
