In [7]:
# 第三题--Series
import pandas as pd
import numpy as np

ser_obj = pd.Series([1, 2, 3, 4, 5])
print(ser_obj)
print('-' * 50)
print(ser_obj.values)
print(type(ser_obj))
print(ser_obj.dtypes)
print(ser_obj.index)
print(ser_obj[0])
print(ser_obj * 2)
print(ser_obj > 3)  # 返回内容是bool类型变量的series
print('-' * 50)
year_data = {2001: 17.8, 2005: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2)
print('-' * 50)
print(ser_obj2.values)
print(ser_obj2.index)
print(ser_obj2[2001])
print(ser_obj2.head())


0    1
1    2
2    3
3    4
4    5
dtype: int64
--------------------------------------------------
[1 2 3 4 5]
<class 'pandas.core.series.Series'>
int64
RangeIndex(start=0, stop=5, step=1)
1
0     2
1     4
2     6
3     8
4    10
dtype: int64
0    False
1    False
2    False
3     True
4     True
dtype: bool
--------------------------------------------------
2001    17.8
2005    20.1
2003    16.5
dtype: float64
--------------------------------------------------
[17.8 20.1 16.5]
Int64Index([2001, 2005, 2003], dtype='int64')
17.8
2001    17.8
2005    20.1
2003    16.5
dtype: float64


In [20]:
# 第三题--DataFrame
t = pd.DataFrame(np.arange(12).reshape(3, 4))
print(t)
print('-' * 50)
array = np.random.randn(5, 4)
print(array)
df_obj = pd.DataFrame(array)
print(df_obj)
# t.loc[1]  # 某一行，这是第0行，类型是Series
print('-' * 50)
d2 = [{"name": "xiaohong", "age": 32, "tel": 10010},
      {"name": "xiaogang", "tel": 10000},
      {"name": "xiaowang", "age": 22}]
df6 = pd.DataFrame(d2)
print(df6)  # 缺失值会用NaN填充
print(type(df6.values))  # ndarray

# pd.Series(1, index=list(range(3,7)), dtype='float32')  # 1是值
print('-' * 50)
dict_data = {'A': 1,
             'B': pd.Timestamp('20190926'),
             'C': pd.Series(1, index=list(range(4)), dtype='float32'),
             'D': np.array([1, 2, 3, 4], dtype='int32'),
             'E': ["Python", "Java", "C++", "C"],
             'F': 'wangdao'}
df_obj2 = pd.DataFrame(dict_data)
print(df_obj2)  # dataframe的不同列可以是不同类型，但是同一列必须是相同类型;且如'A'只有一个值的可以广播
print(df_obj2.index)  # 不可改变
print(df_obj2.columns)  # 列索引
print(df_obj2.dtypes)  # 每一列的数据类型--Series
print('-' * 50)
dates = pd.date_range('20130101', periods=6)  #默认freq='D'，从2013-1-1到2013-1-6
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)
print('-' * 50)
print(df.index)
print(df_obj2['B'])  # Series类型，按照列名提取
df_obj2['G'] = df_obj2['D'] + 4  # 按列增加数据，列名自定义
print(df_obj2)

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
--------------------------------------------------
[[ 0.95221858 -0.08927047 -0.40611974  0.13545468]
 [-0.87711601 -0.12915144  0.75830886  0.16042835]
 [-0.50931637 -1.72344628  0.82996919 -0.19565816]
 [ 0.84030749 -1.0253723  -0.620822    0.27412633]
 [ 0.50947245 -0.6333979   0.65301136 -0.40241075]]
          0         1         2         3
0  0.952219 -0.089270 -0.406120  0.135455
1 -0.877116 -0.129151  0.758309  0.160428
2 -0.509316 -1.723446  0.829969 -0.195658
3  0.840307 -1.025372 -0.620822  0.274126
4  0.509472 -0.633398  0.653011 -0.402411
--------------------------------------------------
       name   age      tel
0  xiaohong  32.0  10010.0
1  xiaogang   NaN  10000.0
2  xiaowang  22.0      NaN
<class 'numpy.ndarray'>
--------------------------------------------------
   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0

In [28]:
# 第三题--索引和函数应用
ser_obj = pd.Series(range(5), index=list('ABCDE'))
print(ser_obj)
print(ser_obj.index)
print(ser_obj['B'])  # 索引名
print(ser_obj[2])  # 位置索引
print(ser_obj.loc['B'])  # loc就是列名
print(ser_obj.iloc[2])  # iloc就是位置
print(ser_obj.iloc[1:3])  # 连续
print(ser_obj.loc['B':'D'])
print(ser_obj.iloc[[0, 2, 4]])  # 不连续索引
print(ser_obj.loc[['A', 'E']])
ser_bool = ser_obj > 2
print(ser_bool)
print('-' * 50)
print(ser_obj[ser_obj > 2])  # 取出大于2的元素

A    0
B    1
C    2
D    3
E    4
dtype: int64
Index(['A', 'B', 'C', 'D', 'E'], dtype='object')
1
2
1
2
B    1
C    2
dtype: int64
B    1
C    2
D    3
dtype: int64
A    0
C    2
E    4
dtype: int64
A    0
E    4
dtype: int64
A    False
B    False
C    False
D     True
E     True
dtype: bool
--------------------------------------------------
D    3
E    4
dtype: int64


In [43]:
# 第三题--DataFrame索引
df_obj = pd.DataFrame(np.random.randn(6, 4), columns=list('ABCD'))
print(df_obj)
print(df_obj['A'])  # Series类型--列
print(df_obj[['A']])  # DataFrame类型
# 用：完成的截取和用loc效果一样，但用loc效率更高
print(ser_obj.loc['A':'C'])  # 类似于闭区间
print(df_obj.loc[0])  # 行
print('-' * 50)
print(df_obj.loc[0:2, 'A':'C'])  # 连续索引
print(df_obj.loc[[0, 2], ['A', 'C']])  # 不连续索引
print(df_obj.loc[[0], ['B']])  # 取单个值，具体效果类似于上面，返回的是dataframe
print(df_obj.loc[0, 'B'])  # 具体值

          A         B         C         D
0 -0.500416  0.055067 -1.167900  0.036211
1 -0.008852 -0.322541  1.123225 -1.474796
2  2.434015 -0.776566 -0.109902  0.486137
3 -0.348089  1.068595 -1.186479 -1.608817
4 -2.071762  1.108538 -0.179846 -0.235114
5 -2.582808  0.710917  1.009342 -0.353903
0   -0.500416
1   -0.008852
2    2.434015
3   -0.348089
4   -2.071762
5   -2.582808
Name: A, dtype: float64
          A
0 -0.500416
1 -0.008852
2  2.434015
3 -0.348089
4 -2.071762
5 -2.582808
A    0
B    1
C    2
dtype: int64
A   -0.500416
B    0.055067
C   -1.167900
D    0.036211
Name: 0, dtype: float64
--------------------------------------------------
          A         B         C
0 -0.500416  0.055067 -1.167900
1 -0.008852 -0.322541  1.123225
2  2.434015 -0.776566 -0.109902
          A         C
0 -0.500416 -1.167900
2  2.434015 -0.109902
          B
0  0.055067
0.055067046826669616


In [48]:
# 第三题--iloc索引
print(ser_obj.iloc[1:3])  # 前闭后开
print(df_obj.iloc[0:2, 0: 1])  # 不再用列名作为index
print(df_obj.iloc[[0, 2], [0, 2]])  # 不连续索引
print(df_obj.iloc[0, 0])  # 取一个值

B    1
C    2
dtype: int64
          A
0 -0.500416
1 -0.008852
          A         C
0 -0.500416 -1.167900
2  2.434015 -0.109902
-0.5004156598801641


In [56]:
# 第三题--函数
df = pd.DataFrame(np.random.randn(5, 4) - 1)
print(df)
print(np.abs(df))  # 绝对值
print(df.apply(lambda x: x.max()))  # apply自己写的函数，应该也可以调用一个函数
print(df.apply(lambda x: x.max(), axis=1))  # 作用在行

          0         1         2         3
0 -1.885957 -2.089832 -0.761772 -0.191912
1 -3.443653  0.135745 -0.396520 -1.350208
2 -1.693516 -0.366916 -1.242741 -0.174284
3 -3.141678 -1.690735 -1.553679  0.252613
4 -1.058424  0.799673 -0.704989 -0.911522
          0         1         2         3
0  1.885957  2.089832  0.761772  0.191912
1  3.443653  0.135745  0.396520  1.350208
2  1.693516  0.366916  1.242741  0.174284
3  3.141678  1.690735  1.553679  0.252613
4  1.058424  0.799673  0.704989  0.911522
0   -1.058424
1    0.799673
2   -0.396520
3    0.252613
dtype: float64
0   -0.191912
1    0.135745
2   -0.174284
3    0.252613
4    0.799673
dtype: float64


AttributeError: 'DataFrame' object has no attribute 'map'

In [61]:
# 第四题--添加和删除nan
df_data = pd.DataFrame([np.random.randn(3), [1., 2., np.nan],
                        [np.nan, 4., np.nan], [1., 2., 3.]])
print(df_data.iloc[2, 0])
print(df_data.isnull())  # 判断数据是否有空
print(df_data.isnull().sum() / len(df_data))  # 数据缺失率
print(df_data.dropna(subset=[0]))  # 是指按第一列来删除,第一列有空值就删除对应的行
print(df_data.dropna(axis=1))  #某列由nan就删除该列
print(df_data.iloc[:, 0].fillna(-100.))  # 将nan用-100.填充
print(df_data)  # 原值不变

for i in df_data.columns:
    print(df_data.loc[:, i])  # 依次拿到每一列

df_data.iloc[:, 2] = df_data.iloc[:, 2].fillna(df_data.iloc[:, 2].mean())  # 用均值填充nan
print(df_data)

nan
       0      1      2
0  False  False  False
1  False  False   True
2   True  False   True
3  False  False  False
0    0.25
1    0.00
2    0.50
dtype: float64
          0        1         2
0  0.347792  0.17041  0.045135
1  1.000000  2.00000       NaN
3  1.000000  2.00000  3.000000
         1
0  0.17041
1  2.00000
2  4.00000
3  2.00000
0      0.347792
1      1.000000
2   -100.000000
3      1.000000
Name: 0, dtype: float64
          0        1         2
0  0.347792  0.17041  0.045135
1  1.000000  2.00000       NaN
2       NaN  4.00000       NaN
3  1.000000  2.00000  3.000000
0    0.347792
1    1.000000
2         NaN
3    1.000000
Name: 0, dtype: float64
0    0.17041
1    2.00000
2    4.00000
3    2.00000
Name: 1, dtype: float64
0    0.045135
1         NaN
2         NaN
3    3.000000
Name: 2, dtype: float64


In [63]:
# 第四题--统计与计算
index1 = pd.MultiIndex.from_arrays([['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'c', 'd', 'd', 'd'],
                                    [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]], names=['cloth', 'size'])

ser_obj = pd.Series(np.random.randn(12), index=index1)
df_obj = ser_obj.unstack(0)
print(df_obj)
#计算最小值有空值如何处理
df_obj.loc[0, 'b'] = np.nan
print(df_obj)
print('-' * 50)
print(df_obj.min(axis=0))

print(df_obj.describe())  # 观察数据分布
print(df_obj.loc[:, 'c'].argmin())  #argmin和argmax只能是series，不能是df
df_obj.idxmin(axis=0, skipna=True)

cloth         a         b         c         d
size                                         
0     -1.291181  1.360183 -0.028372 -0.181576
1     -0.116309 -0.011143  0.270045  0.622838
2      1.227948 -0.476246 -1.162383  1.747675
cloth         a         b         c         d
size                                         
0     -1.291181       NaN -0.028372 -0.181576
1     -0.116309 -0.011143  0.270045  0.622838
2      1.227948 -0.476246 -1.162383  1.747675
--------------------------------------------------
cloth
a   -1.291181
b   -0.476246
c   -1.162383
d   -0.181576
dtype: float64
cloth         a         b         c         d
count  3.000000  2.000000  3.000000  3.000000
mean  -0.059847 -0.243695 -0.306903  0.729646
std    1.260513  0.328877  0.755743  0.969050
min   -1.291181 -0.476246 -1.162383 -0.181576
25%   -0.703745 -0.359971 -0.595377  0.220631
50%   -0.116309 -0.243695 -0.028372  0.622838
75%    0.555819 -0.127419  0.120837  1.185257
max    1.227948 -0.011143  0.270045  1.74767

cloth
a    0
b    2
c    2
d    0
dtype: int64