In [3]:
# 第二题
import numpy as np
import time

a = [i for i in range(10000000)]
b = np.array(a)

a_start_time = time.time()
sum(a)
a_end_time = time.time()
b_start_time = time.time()
b.sum()
b_end_time = time.time()
print(f'列表求和所耗时间{a_end_time - a_start_time}')
print(f'numpy数组求和所耗时间{b_end_time - b_start_time}')

列表求和所耗时间0.12700581550598145
numpy数组求和所耗时间0.003000020980834961


In [16]:
# 第三题
list_2 = [[1, 2, 3], [4, 5, 6]]
array_2 = np.array(list_2)
print(array_2.ndim)  # 维度
print(array_2.shape)  # 形状（行，列）
print(array_2.size)  # 元素数
print(array_2.dtype)  # 数据类型--默认为int32
array_3 = array_2.reshape(3, 2)  # 调整形状
print(array_3.shape)
array_4 = array_2.reshape((1, 6), order='C')
print(array_4)
print(array_4.shape)
array_flatten = array_2.flatten()  # reshape(6,)和flatten效果一样
print(array_flatten.shape)
list_3 = array_3.tolist()  # 转列表
print(list_3)
t = np.arange(24)
print(t)
print(f'shape:{t.shape}')
print(f'维数:{t.ndim}')
t1 = t.reshape((4, 6))
print(t1)
print(t1.shape)
t2 = t1.reshape((2, 3, 4))
print(t2)
print(t2.shape)
print(t2.ndim)  # 2--0轴，3--1轴,4--2轴

2
(2, 3)
6
int32
(3, 2)
[[1 2 3 4 5 6]]
(1, 6)
(6,)
[[1, 2], [3, 4], [5, 6]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
shape:(24,)
维数:1
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
3


In [20]:
#  第四题
import random

f = np.array([1, 2, 3, 4, 127], dtype=np.int8)
print(f.itemsize)  # 1字节
print(f.dtype)
f[4] = f[4] + 1
# f[4]  # 溢出

f1 = f.astype(np.int64)
print(f1.dtype)
print(f1.itemsize)
print(round(random.random(), 2))
arr = np.array([random.random() for _ in range(10)])
print(arr)
print(arr.itemsize)
print(arr.dtype)
print(np.round(arr, 2))

1
int8
int64
8
0.9
[0.01881145 0.27009757 0.91653923 0.03038046 0.64487586 0.55540659
 0.96650984 0.89957584 0.14264792 0.76547804]
8
float64
[0.02 0.27 0.92 0.03 0.64 0.56 0.97 0.9  0.14 0.77]


In [27]:
t1 = np.arange(24).reshape((6,4))
print(t1)
t2 = t1.tolist()
print(t1+2)
print(t1*2)
print(t1/2)
print('-'*50)
t3 = np.arange(100,124).reshape((6,4)) # 同型ndarray可以运算
print(t1+t3)
print(t1*t3)
t1 = t1.reshape((4,6))
t4 = np.arange(6).reshape((1,6))
print(t4.shape)
print(t1-t4)
t5 = np.arange(4).reshape((4,1))
print(t1-t5)
print('-'*50)
a = np.arange(24).reshape((2,3,4))
b = np.arange(12).reshape((1,3,4))
a-b  # ndim相同,支持某一轴的size不同，但其中一个ndarary的size为1

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]
--------------------------------------------------
[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]
(1, 6)
[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]
[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]
--------------------------------------------------


array([[[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[12, 12, 12, 12],
        [12, 12, 12, 12],
        [12, 12, 12, 12]]])

In [35]:
# 第五题
m = np.arange(10)
print(m[0],m)
print(m[2:])
print(m[2:8:2])  # 类似于list的切片
t1 = np.arange(24).reshape((4,6))
print(t1)
print(t1[1])
print(t1[1:])
print(t1[1:3, :])  # 逗号后面是列
print(t1[[0,2,3]])  # 不连续的行

print(t1[:,1])
print(t1[[0,1,1],[0,2,3]])  # 第0行第0个，第1行第2个， 第1行第3个

0 [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[ 6  7  8  9 10 11]
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[ 1  7 13 19]
[0 8 9]


In [39]:
# 第五题--修改
t = np.arange(24).reshape((4,6))
print(t)
t = t.clip(10,18)  # 允许的值在10~18内，若小于10则改为10，若大于18则改为18
print(t)
t = np.arange(24).reshape((4,6))
print(t<10)
score = np.array([[80, 88], [82, 81], [75, 81]])
print(score)
result = np.where(score < 80, True, False)  # 三目运算符,类似于C的？：
print(result)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[10 10 10 10 10 10]
 [10 10 10 10 10 11]
 [12 13 14 15 16 17]
 [18 18 18 18 18 18]]
[[ True  True  True  True  True  True]
 [ True  True  True  True False False]
 [False False False False False False]
 [False False False False False False]]
[[80 88]
 [82 81]
 [75 81]]
[[False False]
 [False False]
 [ True False]]


In [45]:
# 第六题
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(np.append(a,[7,8,9]))  # flatten了
print(a)  # a没变
print(np.append(a, [[7, 8, 9]], axis=0))
print(a)
print(np.append(a, [[5, 5, 5], [7, 8, 9]], axis=1))
print(a)

# insert插入
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
print(np.insert(a, 1, [11, 22]))
print(np.insert(a, 1, [11, 12], axis=0))  #那个轴插入，哪个轴size变大
print(np.insert(a, 1, 11, axis=0))
print(np.insert(a, 1, [1, 2, 5], axis=1))

# 删除
a = np.arange(12).reshape(3, 4)
print(np.delete(a, 5))  # 先展成一维，再删除
print(a)
print(np.delete(a, 1, axis=0))
print(np.delete(a, 1, axis=1))

# unique
a = np.array([5, 2, 6, 2, 7, 5, 6, 9, 8, 2])
u, indices = np.unique(a, return_inverse=True)
print(u)
print(indices)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[ 1 11 22  2  3  4  5  6]
[[ 1  2]
 [11 12]
 [ 3  4]
 [ 5  6]]
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]
[[1 1 2]
 [3 2 4]
 [5 5 6]]
[ 0  1  2  3  4  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]
[2 5 6 7 8 9]
[1 0 2 0 3 1 2 5 4 0]


In [46]:
# numpy数学计算
score = np.array([[80, 88], [82, 81], [75, 81]])
print(score)
# 1. 获取所有数据最大值
result = np.max(score)
print(result)
# 2. 获取某一个轴上的数据最大值，对应的轴就消失
result = np.max(score, axis=1)
print(result)
# 3. 获取最小值
result = np.min(score)
print(result)
# 4. 获取某一个轴上的数据最小值
result = np.min(score, axis=0)
print(result)
# 5. 数据的比较
result = np.maximum([-2, -1, 0, 1, 2], 0)  # 第一个参数中的每一个数与第二个参数比较返回大的
print(result)
result = np.minimum([-2, -1, 0, 1, 2], 0)  # 第一个参数中的每一个数与第二个参数比较返回小的
print(result)
result = np.maximum([-2, -1, 4, 1, 2], [1, 2, 3, 4, 5])
print(result)
result = np.mean(score)  # 获取所有数据的平均值
print(result)
result = np.mean(score, axis=0)  # 获取某一行或者某一列的平均值
print(result)
# 7. 求前缀和
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.cumsum(axis=0))

[[80 88]
 [82 81]
 [75 81]]
88
[88 82 81]
75
[75 81]
[0 0 0 1 2]
[-2 -1  0  0  0]
[1 2 4 4 5]
81.16666666666667
[79.         83.33333333]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [5 7 9]]
